### ISSUE TITLE
Files with identical names write over each other.

### ISSUE THREAD

**Issue by dvcky** [Ghost0159/hShop-downloader#1]
Hi,

I was recently using your tool, when I came across an issue. It turns out there are quite a few files in the Themes section that are identical in name. As such, the script will download whatever file comes first, and then overwrites that file with the next one with the same name. For an example, look up "I Saurini e il Flusso Magico" and try downloading the two themes that appear - they are identical in filename.

This appears to be the case for this theme as well as ~50 others, and as such some files are missing in the bulk download. Luckily this seems to be an issue mostly exclusive to themes, with the "Super Mario Bros. Next: Sunset Shores" ROM hack being the only other instance of the issue.

What might be a good way to fix this? Could a special case be added for the duplicates where the hShop ID is appended to the end for further differentiation?

**Comment by Ghost0159** [comment]
Thank you for the info.
I will fix this problem this weekend, I think, but I admit that I'm not exactly sure what the best way would be. Including the identifier might be interesting, but how should I include it? 

Maybe like this:
NameOfTheFiles.....(...)...[hID:3457].cia

**Comment by dvcky** [comment]
I think that could be a pretty good template for it, but I might recommend utilizing a "safer character" like a hyphen over a colon (example: `NameOfTheFiles.....(...)...[hID-3457].cia`), as colons are invalid characters for the windows filesystem.

**Comment by dvcky** [comment]
I've brainstormed some quick pseudocode that should work decently for this situation:

.

---
_(run this for each subcategory)_
1. Create a dict with this template:
```
Key - Name of downloaded file
Value - hShop ID (grab this while downloading each file)
```
2. Before each download, grab what the filename would be if it were to be downloaded:

If the filename exists as a key in the dict, do a couple things:
```
First, rename the older file (if it has not been renamed in a previous duplication check) to include the appended hShop ID with whatever template you prefer (in our case, [hID-XXXXX]).

Then, change the name of the new file that hasn't been downloaded yet to include the appended hShop ID template. With the correct filename, we can now check if this file has been downloaded previously.

OPTIONAL: Include duplicates in a log file? So that user knows which files has filenames not identical to those from hShop originally.

Don't change the values in the dict though! In the case that there are even more duplicates of the same item, we want to make sure it is able to catch them.
```

If the filename does not exist as a key in the dict, append it to the dict for future reference.

---

.

The downside to this implementation is that it will use slightly more memory (storing the dict with all the keys and values) and will always download the first of the duplicates if a bulk download action is run again, but re-downloading only one of the duplicates as opposed to re-downloading all of them and overwriting them is an improvement!

It's also much more complicated in implementation than hard-coding values, but its made with scalability in mind in the off-chance that there are more duplicates that are added/changed in the future.

Hope this helps!

**Comment by Ghost0159** [comment]
ok, could you please test this?
https://github.com/Ghost0159/hShop-downloader/tree/fix-identical-names

**Comment by dvcky** [comment]
Looks good to me! Personally I would prefer for it to only tag duplicates because the file names can get a bit messy (hence my pseudocode), but that's just me, and this creates a standard template for the whole collection. Thanks for making the change!
