### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by guellenmade** [Ghost0159/hShop-downloader#3]
Hi
I realy love your script and thanke you for making it.
But i have a Bug (or maybe i am dumb) that crashes the script.
![image](https://github.com/user-attachments/assets/07116a82-0320-4953-a72b-a2b5d0f29e83)
Can you please help me or fix the Script?
Thank you :)

**Comment by Ghost0159** [comment]
Hi,
When you have their error ?

What did you have try ?
* Game, Updates or other ?

**Comment by guellenmade** [comment]
It started last week or so

I cloned this github repository again

I tried to download every game in europe

**Comment by Ghost0159** [comment]
Normally, this should be working now. Could you please try again and let me know if everything is okay for you?

Script with fix : [hshop_downloader.py](https://github.com/Ghost0159/hShop-downloader/blob/b5d57c1540f2d3cce3e81c9a7c4900de672bfd96/hshop_downloader.py)

**Comment by guellenmade** [comment]
Thank you sooo much you are the best :)
