### ISSUE TITLE
Unclear Instructions

### ISSUE THREAD

**Issue by SammyBoy128** [Ghost0159/hShop-downloader#5]
I find myself unable to use the script because of the lack of instructions on how to install the resources necessary to run the script. How do I install the program on my pc?

**Comment by Ghost0159** [comment]
just read: https://github.com/Ghost0159/hShop-downloader?tab=readme-ov-file#prerequisites

**Comment by Ghost0159** [comment]
just read: https://github.com/Ghost0159/hShop-downloader?tab=readme-ov-file#prerequisites

and also know a little python and how to use it
